# This dict is used to find the row on the team stats based on the type of play
CHANCE_ROW_MAPPING = {
    "rush_type1":                   {"Tasavoimainen": 10, "Ylivoimainen": 11, "Alivoimainen": 12, "Läpiajo": 13},
    "takeaway_type":                {"HAPP/PAHP": 15, "KAPP/KAHP": 17, "PAPP/HAHP": 19, "Jatkopaine": 21},
    "hahp_papp_type":               {"Täyttö": 23, "Alapeli": 25, "Yläpeli": 27},
    "rebound_type":                 {"SHP": 29, "Riisto/Menetys": 29, "HAHP/PAPP": 29},
    "faceoff_type":                 {"Hyökkäysalue": 31, "Keskialue": 31, "Puolustusalue": 31},
    "v5v5_other_type":              {"IM": 33, "TM": 33, "4v4": 33},
    "pp_faceoff_entry_type":        {"Aloitus Vasen": 38, "Aloitus Oikea": 38, "Haku / vastaanotto": 38},
    "pp_shot_deflection_low_type1": {"Päädystä": 40, "Siiveltä": 41, "Keskeltä": 42, "Viivasta": 43},
    "pp_blueline_shot_type":        {"Suora": 45, "Ohjuri": 45, "Rebound": 45},
    "pp_pressure_brokenplay_type":  {"Paine": 47, "Riisto": 47, "Brokenplay": 47},
    "pp_other_type":                {"Kuljetus": 49, "Punnerrus": 49, "Rebound": 49},
    "pp_5vs3_type":                 {"Suora": 51, "Ohjuri": 51, "Rebound": 51},
    "pp_av_yv_type":                {"Läpiajo": 53, "YV": 53, "TV": 53},
    "v3vs3_type":                   {"Aloitus": 58, "Hallinta": 58, "Riisto / Menetys": 58},
    "ps_type":                      {"Laukaus": 60, "Harhautus": 60, "Muu": 60},
}

FINAL_COLUMNS = [
    "rush_type2",
    "takeaway_happ_pahp_type",
    "takeaway_kapp_kahp_type",
    "takeaway_papp_hahp_type",
    "takeaway_jatkopaine_type",
    "hahp_papp_taytto_type",
    "hahp_papp_alapeli_type",
    "hahp_papp_ylapeli_type",
    "rebound_type",
    "faceoff_type",
    "v5v5_other_type",
    "pp_faceoff_entry_type",
    "pp_shot_deflection_low_type2",
    "pp_blueline_shot_type",
    "pp_pressure_brokenplay_type",
    "pp_other_type",
    "pp_5vs3_type",
    "pp_av_yv_type",
    "v3vs3_type",
    "ps_type",
]

VALUE_TO_CHANCE_COLUMN = {
    "PAHP": "G",
    "1. Paine": "G",
    "Syöttö": "G",
    "Pohja": "G",
    "Murtautuminen": "G",
    "Syöttö sisään": "G",
    "Suora": "G",
    "SHP": "G",
    "Hyökkäysalue": "G",
    "IM": "G",
    "Aloitus Vasen": "G",
    "Kesk. / Pääty.": "G",
    "Paine": "G",
    "Kuljetus YV": "G",
    "Läpiajo": "G",
    "Aloitus": "G",
    "Laukaus": "G",

    "KAHP": "H",
    "2. Paine": "H",
    "Kuljetus": "H",
    "Half Board": "H",
    "Syöttö 3:lle": "H",
    "Murtautuminen sisään": "H",
    "Ohjaus": "H",
    "Riisto/Menetys": "H",
    "Keskialue": "H",
    "TM": "H",
    "Aloitus Oikea": "H",
    "Vasen Siipi": "H",
    "Ohjuri": "H",
    "Riisto": "H",
    "Punnerrus": "H",
    "Ohjuri": "H",
    "YV": "H",
    "Hallinta": "H",
    "Harhautus": "H",

    "Kääntö": "I",
    "3. / Puolustajan Paine": "I",
    "Muu": "I",
    "Viiva": "I",
    "Syöttö 4/5:lle": "I",
    "HAHP/PAPP": "I",
    "Puolustusalue": "I",
    "4v4": "I",
    "Haku / vastaanotto": "I",
    "Oikea siipi": "I",
    "Rebound": "I",
    "Brokenplay": "I",
    "TV": "I",
    "Riisto / Menetys": "I"
}

RESULT_TO_SHIFT_MAP = {
    "Maali +": 0,
    "Maali -": 3,
    "MP +": 6,
    "MP -": 9
}