"""Add powerplay and penalty kill values to games. Set db default to NULL to recognize prior games

Revision ID: 10515b76b444
Revises: ee57760fc222
Create Date: 2025-09-14 16:56:57.397108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10515b76b444'
down_revision: Union[str, None] = 'ee57760fc222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('powerplays', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('penalty_kills', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'penalty_kills')
    op.drop_column('games', 'powerplays')
    # ### end Alembic commands ###
