"""remove player cascades and add game cascades

Revision ID: ee57760fc222
Revises: 
Create Date: 2025-09-13 23:47:02.762112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee57760fc222'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('games_in_roster_game_id_fkey'), 'games_in_roster', type_='foreignkey')
    op.drop_constraint(op.f('games_in_roster_player_id_fkey'), 'games_in_roster', type_='foreignkey')
    op.create_foreign_key(None, 'games_in_roster', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'games_in_roster', 'players', ['player_id'], ['id'])
    op.drop_constraint(op.f('player_stats_tag_on_ice_player_id_fkey'), 'player_stats_tag_on_ice', type_='foreignkey')
    op.create_foreign_key(None, 'player_stats_tag_on_ice', 'players', ['player_id'], ['id'])
    op.drop_constraint(op.f('player_stats_tag_participating_player_id_fkey'), 'player_stats_tag_participating', type_='foreignkey')
    op.create_foreign_key(None, 'player_stats_tag_participating', 'players', ['player_id'], ['id'])
    op.drop_constraint(op.f('player_stats_tags_game_id_fkey'), 'player_stats_tags', type_='foreignkey')
    op.create_foreign_key(None, 'player_stats_tags', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.add_column('players', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.drop_constraint(op.f('team_stats_tags_game_id_fkey'), 'team_stats_tags', type_='foreignkey')
    op.create_foreign_key(None, 'team_stats_tags', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_stats_tags', type_='foreignkey')
    op.create_foreign_key(op.f('team_stats_tags_game_id_fkey'), 'team_stats_tags', 'games', ['game_id'], ['id'])
    op.drop_column('players', 'is_active')
    op.drop_constraint(None, 'player_stats_tags', type_='foreignkey')
    op.create_foreign_key(op.f('player_stats_tags_game_id_fkey'), 'player_stats_tags', 'games', ['game_id'], ['id'])
    op.drop_constraint(None, 'player_stats_tag_participating', type_='foreignkey')
    op.create_foreign_key(op.f('player_stats_tag_participating_player_id_fkey'), 'player_stats_tag_participating', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'player_stats_tag_on_ice', type_='foreignkey')
    op.create_foreign_key(op.f('player_stats_tag_on_ice_player_id_fkey'), 'player_stats_tag_on_ice', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'games_in_roster', type_='foreignkey')
    op.drop_constraint(None, 'games_in_roster', type_='foreignkey')
    op.create_foreign_key(op.f('games_in_roster_player_id_fkey'), 'games_in_roster', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('games_in_roster_game_id_fkey'), 'games_in_roster', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###
